### PR TITLE
Update the blog article template with new properties

### PR DESCRIPTION
**Pull request by fakela**

### CODE REVIEW

**Review by fharper — CHANGES_REQUESTED** [review]
Markdown isn't valid. Before asking a review, check if all the tests are green and if they aren't, that it's not, let's fix them (unless it's fixed in another PR we are waiting to merge)

**Comment by fakela** [comment]
> Markdown isn't valid. Before asking a review, check if all the tests are green and if they aren't, that it's not, let's fix them (unless it's fixed in another PR we are waiting to merge

**Comment by fakela** [comment]
> > Markdown isn't valid. Before asking a review, check if all the tests are green and if they aren't, that it's not, let's fix them (unless it's fixed in another PR we are waiting to merge


I don't know why it's still having Markdown error 😢

**Review by fharper — APPROVED** [review]
LGTM

**Pull request merged**
