### PR TITLE
Add blog post template

### PR DESCRIPTION
**Pull request by fakela**

### CODE REVIEW

**Review by fharper — CHANGES_REQUESTED** [review]
You need to update the link in the writing readme file

**Review by fharper — APPROVED** [review]
LGTM

**Review by fharper — CHANGES_REQUESTED** [review]
@fakela some commits were not signed 😅

**Comment by fakela** [comment]
It has the verified mark now

**Comment by fakela** [comment]
> @fakela some commits were not signed 😅

It has the verified mark now

**Comment by fharper** [comment]
You need to either verify the previous commits on this branch, or rewrite history to remove them as all commits need to be verified and there's only 2 out of 4.

**Pull request closed without merging**
